Component({
  data:{
    list:[{
      des:"我的邀约",
      url:'/pages/myInfo/myAppoint/myAppoint'
    },{
      des:"我的表白",
      url:'/pages/myInfo/myLove/myLove'
    },{
      des:"我的信息",
      url:'/pages/myInfo/myMes/myMes'
    }]
  },
  created:function(){
    wx.setNavigationBarColor({
      backgroundColor:'#5D98F6',
      frontColor:'#ffffff',
      animation:{}
    })
  },
  methods:{
    goMes:function(e){
      wx.navigateTo({
        url: e.currentTarget.dataset['url']
      })
    }
  }
})