Component({
  data:{
    list:['我的邀约','我的表白','我的信息']
  },
  created:function(){
    wx.setNavigationBarColor({
      backgroundColor:'#5D98F6',
      frontColor:'#ffffff',
      animation:{}
    })
  },
})